server:
  port: ${AUTH_SERVICE_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: user_client_api

  datasource:
    url: jdbc:postgresql://${DB_URI:localhost}:${DB_PORT:5432}/notification
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: user_client_db
    open-in-view: false

  kafka:
    consumer:
      group-id: ${KAFKA_GROUP_ID:1001}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092
    producer:
      send-event-create-account-topic: CreateAccountEventTopic
      send-event-notification-topic: NotificationEventTopic
      send-event-confirmed-account-topic: ConfirmedAccountEventTopic

  integration:
    email-token:
      expiration-date: 900000
      hash-digits: 6